FlightBook/urls.py
from django.contrib import admin
from django.urls import path, include
from members import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", views.register, name="members"),
    path('', include('members.urls')),
    path('', include("django.contrib.auth.urls")),
    path('booking/', include('booking.urls')),
    path('management/', include('management.urls')),
    path('cancellation/', include('cancellation.urls')),
]

booking/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('flight/', views.FlightSelectView.as_view(), name='booking-flight'),
    path('<flight>/seat/', views.seatselect, name='booking-seat'),
    path('<pk>/info/', views.InfoCollectView.as_view(), name='booking-info'),
    path('<booking>/pay/', views.payment, name='booking-pay'),
    path('<booking>/confirm/', views.confirmation, name='booking-confirm'),
]

booking/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Plane(models.Model):
    planeID = models.CharField(max_length=5, primary_key=True, unique=True)
    planeType = models.CharField(max_length=10)
    seatsAvailable = models.IntegerField()
    seatsPerRow = models.IntegerField()
    seatsEconomyClass = models.IntegerField()
    seatsBusinessClass = models.IntegerField()
    seatsFirstClass = models.IntegerField()


class Flight(models.Model):
    flightNo = models.CharField(max_length=5)
    airline = models.CharField(max_length=100)
    seatsAvailable = models.IntegerField()
    departureLocation = models.CharField(max_length=100)
    arrivalLocation = models.CharField(max_length=100)
    flightDateTime = models.DateTimeField()
    flightDuration = models.CharField(max_length=20)
    departureTerminal = models.CharField(max_length=3)
    planeID = models.ForeignKey(Plane, on_delete=models.CASCADE)
    economyCost = models.DecimalField(default=0, decimal_places=2, max_digits=12)
    businessCost = models.DecimalField(default=0, decimal_places=2, max_digits=12)
    firstCost = models.DecimalField(default=0, decimal_places=2, max_digits=12)

class Ticket_History(models.Model):
    ECONOMY = 'e'
    BUSINESS = 'b'
    FIRST = 'f'
    CLASS_CHOICES = [
        (ECONOMY, 'Economy Class'),
        (BUSINESS, 'Business Class'),
        (FIRST, 'First Class')
    ]

    bookingRef = models.CharField(max_length=6)
    seatNo = models.CharField(max_length=3)
    passenger_passportNo = models.CharField('Passanger ID/Passport Number', max_length=13)
    booked_MemberID = models.ForeignKey(User, on_delete=models.CASCADE)
    passengerNames = models.CharField('Passanger Name', max_length=100)
    passengerSurname = models.CharField('Passanger Surname',max_length=100)
    flightNo = models.ForeignKey(Flight, on_delete=models.CASCADE)
    seatClass = models.CharField(max_length=1, choices=CLASS_CHOICES, default=ECONOMY)
    ticket_Cancelled = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)

booking/forms.py
from django import forms

class PayementForm(forms.Form):
    '''
    Class for payment form.
    Extends forms.Form
    '''
    name = forms.CharField(label='Name on Card', max_length=100)
    cardNo = forms.CharField(label='Card Number', max_length=16)
    cvv = forms.CharField(label='CVV', max_length=4)

booking/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, UpdateView
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponseForbidden
from .models import Flight, Ticket_History
from .forms import PayementForm
import random
from django.contrib import messages
from datetime import datetime

class FlightSelectView(ListView):
    '''
    Displays all available flights.
    Extends ListView Default View
    '''
    model = Flight
    context_object_name = 'flights'
    ordering = 'flightDateTime'

    def get_queryset(self):
        qs = self.model.objects.filter(flightDateTime__gt=datetime.now()).order_by(self.ordering)
        return qs

@login_required
def seatselect(request, flight):
    '''
    Renders seat selection template.
    On Post Request it determines the selected seats
    and calls InfoCollectView.
    This places relevant ticket info into request.session
    '''
    letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    # Checks if request is POST
    if request.method == "POST":
        if len(request.POST) > 1:
            args = request.POST.keys()
            booking = str(random.randint(100000, 999999))   # Generating Booking Number
            seats = []
            # Determining number of types of seats
            classesNo = {
                'e':0,
                'b': 0,
                'f': 0,
            }
            for val in args:
                if val != "csrfmiddlewaretoken":
                    seats.append(((letters[int(val[-2])] + str(val[2:-4])), val[0]))
                    classesNo[val[0]] +=1
            ids=[]
            # Creating initial entry for seats selected
            for seat in seats:
                ticket = Ticket_History(bookingRef=booking, seatNo=seat[0], flightNo=Flight.objects.get(flightNo=flight), booked_MemberID=request.user, seatClass=seat[1])
                ticket.save()
                ids.append(ticket.id)
            # Loading data into session for next views
            request.session['ids'] = ids
            request.session['NoOfSeats'] = len(ids)
            request.session['order'] = booking
            request.session['classes'] = classesNo
            return redirect('booking-info', pk=ids[0])
        else:
            messages.error = (request, 'Please make a selection before submitting')
    # Removing incomplete ticket entries
    Ticket_History.objects.filter(passenger_passportNo__exact='',passengerNames__exact='',passengerSurname__exact='').delete()
    Ticket_History.objects.filter(paid=False).delete()
    # Collecting Context Data to be sent to view
    request.session['flight'] = flight
    flightInfo = Flight.objects.get(flightNo=flight)
    flightHistory = Ticket_History.objects.filter(flightNo=flightInfo, ticket_Cancelled=False)
    taken_seats = [(int(ticket.seatNo[1:]), letters.index(ticket.seatNo[0])) for ticket in flightHistory]
    col = int(flightInfo.planeID.seatsPerRow)
    row = int(flightInfo.planeID.seatsAvailable / col)
    mid = (col//2)
    
    firstMark = (flightInfo.planeID.seatsFirstClass)/col
    busMark = (flightInfo.planeID.seatsBusinessClass/col)+firstMark
    rows = range(1, row+1)
    cols = range(col)
    seats = []

    for r in rows:
        seats.append([])
        for c in cols:
            seats[r-1].append((r,c))

    # Context Data
    context = {
        'flightInfo': flightInfo,
        'seats': seats,
        'col': col,
        'firstMark': firstMark,
        'busMark': busMark,
        'mid': mid,
        'letters': list(letters[:col//2])+['Isle']+list(letters[col//2:col]),
        'takenSeats': taken_seats
    }
    return render(request, "booking/seatselect.html", context)

class InfoCollectView(LoginRequiredMixin, UpdateView):
    '''
    Presents form for outstanding ticket information to user
    Extends UpdateView Default View
    '''
    template_name = 'booking/infocollect.html'
    model = Ticket_History
    fields = ['passenger_passportNo','passengerNames', 'passengerSurname']
    context_object_name = 'context'

    # Checking validity of returned form
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # Determines success url based on whether more seat forms need to be filled or not
    def get_success_url(self):
        if len(self.request.session['ids']) > 1:
            self.request.session['ids'] = self.request.session['ids'][1:]
            return reverse('booking-info',kwargs={'pk': self.request.session['ids'][0]})
        else:
            return reverse('booking-pay', kwargs={'booking': self.request.session['order']})


@login_required
def payment(request, booking):
    '''
    Shows payment breakdown of order.
    Provides a form for bank details.
    '''
    # Checks if request is POST
    if request.method == 'POST':
        form = PayementForm(request.POST)
        # Redirects to confirmation page if form is valid
        if form.is_valid():
            # Decrementing number of available seats for flight
            flight = Flight.objects.get(flightNo=request.session['flight'])
            flight.seatsAvailable = flight.seatsAvailable - request.session['NoOfSeats']
            flight.save()
            return HttpResponseRedirect(reverse('booking-confirm' ,kwargs={'booking': request.session['order']}))
    else:
        form = PayementForm()
    # Collecting Context Data
    orders = Ticket_History.objects.filter(bookingRef=booking)
    flight = Flight.objects.get(flightNo=request.session['flight'])
    classes = request.session['classes']
    prices = {
        'eprice': classes['e']*flight.economyCost,
        'bprice': classes['b']*flight.businessCost,
        'fprice': classes['f']*flight.firstCost,
        'total': classes['e']*flight.economyCost + classes['b']*flight.businessCost + classes['f']*flight.firstCost
    }
    context = {
        'form': form,
        'orders': orders,
        'classes': classes,
        'prices': prices,
        'flight': flight
    }
    # Rendering payment page
    return render(request, 'booking/payment.html', context)

@login_required
def confirmation(request, booking):
    '''
    Displays order confirmation page
    '''
    # Collecting Context Information
    tickets = Ticket_History.objects.filter(bookingRef=booking)
    for ticket in tickets:
        ticket.paid=True
        ticket.save()
    if request.user == tickets[0].booked_MemberID:
        flight = Flight.objects.get(flightNo=request.session['flight'])
        classes = request.session['classes']
        total = classes['e']*flight.economyCost + classes['b']*flight.businessCost + classes['f']*flight.firstCost
        context = {
            'tickets': tickets,
            'total': total,
            'flight': flight,
            'order': request.session['order']
        }
        # Rendering Confirmation Page
        return render(request, 'booking/confirmation.html', context)
    else:
        return HttpResponseForbidden()

booking/templates/booking/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title></title>
  </head>
  <body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

booking/templates/booking/confirmation.html
{% extends "main/base.html" %}
{% block content %}
    <h1>Confirmation for booking #{{order}}</h1>
    <h2>Flight Information</h2>
    <table class='table'>
        <thead>
            <tr>
                <th scope="col">Flight</th>
                <th scope="col">Airline</th>
                <th scope="col">Departure</th>
                <th scope="col">Arrival</th>
                <th scope="col">Departure Terminal</th>
                <th scope="col">Date</th>
                <th scope="col">Flight Duration</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">{{ flight.flightNo }}</th>
                <td>{{ flight.airline }}</td>
                <td>{{ flight.departureLocation }}</td>
                <td>{{ flight.arrivalLocation }}</td>
                <td>{{ flight.departureTerminal }}</td>
                <td>{{ flight.flightDateTime }}</td>
                <td>{{ flight.flightDuration }}</td>
            </tr>
        </tbody>
    </table>
    <h2>Seat Information</h2>
    <table class='table'>
        <thead>
            <tr>
                <th scope="col">Seat Number</th>
                <th scope="col">Seat Type</th>
                <th scope="col">Passanger Name</th>
            </tr>
        </thead>
        <tbody>
            {% for ticket in tickets %}
            <tr>
                <td>{{ ticket.seatNo }}</td>
                <td>{{ ticket.get_seatClass_display }}</td>
                <td>{{ticket.passengerNames}} {{ticket.passengerSurname}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h2>Total Price: R{{total}}</h2>
    <a href="/"><button type="button" class="btn btn-primary">Return to Home</button></a>
{% endblock content %}

booking/templates/booking/flight_list.html
{% extends "main/base.html" %}
{% block content %}
    <h1>Select Flight</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Flight</th>
                <th scope="col">Airline</th>
                <th scope="col">Departure</th>
                <th scope="col">Arrival</th>
                <th scope="col">Date</th>
                <th scope="col">Price</th>
                <th scope="col">Book Now</th>
            </tr>
        </thead>
        <tbody>
            {% for flight in flights %}
                <tr>
                    <th scope="row">{{ flight.flightNo }}</th>
                    <td>{{ flight.airline }}</td>
                    <td>{{ flight.departureLocation }}</td>
                    <td>{{ flight.arrivalLocation }}</td>
                    <td>{{ flight.flightDateTime }}</td>
                    <td>R{{ flight.economyCost }} to R{{flight.firstCost}}</td>
                    {% if flight.seatsAvailable != 0 %}
                        <td><a href="{% url 'booking-seat' flight.flightNo %}"><button type="button" class="btn btn-success">Book</button></a></td>
                    {% else %}
                        <td><button type="button" class="btn btn-danger" disabled>Sold Out</button></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

booking/templates/booking/flight_view.html
{% extends "booking/base.html" %}
{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Flight</th>
                <th scope="col">Airline</th>
                <th scope="col">Departure</th>
                <th scope="col">Arrival</th>
                <th scope="col">Date</th>
                <th scope="col">Book Now</th>
            </tr>
        </thead>
        <tbody>
            {% for flight in flights %}
                <tr>
                    <th scope="row">{{ flight.flightID }}</th>
                    <td>{{ flight.airline }}</td>
                    <td>{{ flight.departureLocation }}</td>
                    <td>{{ flight.arrivalLocation }}</td>
                    <td>{{ flight.dateTime }}</td>
                    <td><a href="#"><button type="button" class="btn btn-success">Book Now</button></a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

booking/templates/booking/infocollect.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Passanger Information for seat {{ context.seatNo }}:</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
{% endblock content %}

booking/templates/booking/payment.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Payment</h1>
    <h2>Order Summary:</h2>
    <table class='table'>
        <thead>
            <tr>
                <th scope="col">Seat Type</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price Per Seat</th>
                <th scope="col">Total</th>
            </tr>
        </thead>
        <tbody>
            {% if classes.e != 0 %}
            <tr>
                <td>Economy Class</td>
                <td>{{classes.e}}</td>
                <td>R{{flight.economyCost}}</td>
                <td>R{{prices.eprice}}</td>
            </tr>
            {% endif %}
            {% if classes.b != 0 %}
            <tr>
                <td>Business Class</td>
                <td>{{classes.b}}</td>
                <td>R{{flight.businessCost}}</td>
                <td>R{{prices.bprice}}</td>
            </tr>
            {% endif %}
            {% if classes.f != 0 %}
            <tr>
                <td>First Class</td>
                <td>{{classes.f}}</td>
                <td>R{{flight.firstCost}}</td>
                <td>R{{prices.fprice}}</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <h3>Total: R{{prices.total}}</h3>
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Card Information:</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
{% endblock content %}

booking/templates/booking/seatselect.html
{% extends "main/base.html" %}
{% block content %}
    <h1>Seat Selection for {{ flightInfo.airline }} flight {{ flightInfo.flightNo }}</h1>
    <div class='container-fluid'>
        <form method="post">
        <div class="row">
            <div class="col">
                {% csrf_token %}
                <table>
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            {% for letter in letters %}
                                <th scope="col">{{ letter }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    {% for seat in seats %}
                        <tr>
                            <td>{{seat.0.0}}</td>
                            {% for pos in seat %}
                                {% if pos.1 == mid %}
                                    <td><div style="width:30px"></div></td>
                                {% endif %}
                                {% if pos in takenSeats %}
                                    <td><label class="taken"for="f[{{ pos.0 }}][{{ pos.1 }}]"></td>
                                {% else %}
                                    {% if pos.0 <= firstMark %}
                                        <td><input class="first" type="checkbox" name="f[{{ pos.0 }}][{{ pos.1 }}]" id="f[{{ pos.0 }}][{{ pos.1 }}]" value="1"><label class="first"for="f[{{ pos.0 }}][{{ pos.1 }}]"></td>
                                    {% elif pos.0 <= busMark %}
                                        <td><input class="bus" type="checkbox" name="b[{{ pos.0 }}][{{ pos.1 }}]" id="b[{{ pos.0 }}][{{ pos.1 }}]" value="1"><label class="bus"for="b[{{ pos.0 }}][{{ pos.1 }}]"></td>
                                    {% else %}
                                        <td><input class="economy" type="checkbox" name="e[{{ pos.0 }}][{{ pos.1 }}]" id="e[{{ pos.0 }}][{{ pos.1 }}]" value="1"><label class="economy"for="e[{{ pos.0 }}][{{ pos.1 }}]"></td>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="col">
                <p>Please select the seats you would like to book.</p>
                <h4>Legend:</h4>
                <div>
                    <table class="table table-sm text-center">
                        <thead>
                            <tr>
                                <th scope="col"><label class="first"></label></th>
                                <th scope="col"><label class="bus"></th>
                                <th scope="col"><label class="economy"></th>
                                <th scope="col"><label class="taken"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>First Class</td>
                                <td>Business Class</td>
                                <td>Economy Class</td>
                                <td>Seat Taken</td>
                            </tr>
                            <tr>
                                <td>R{{flightInfo.firstCost}}</td>
                                <td>R{{flightInfo.businessCost}}</td>
                                <td>R{{flightInfo.economyCost}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
        </div>
    </div>
    <style>
        table {
            background-color: #fff;
            width: 20vw;
        }
     
        input[type=checkbox] {
            display: none;
        }
     
        label.economy {
            width: 30px;
            height: 30px;
            border-radius: 4px;
            background-color: #3498db;
        }
     
        input.economy:checked+label {
            background-color: #1f8528;
            border: 2px solid #2c3e50;
        }

        label.first {
            width: 30px;
            height: 30px;
            border-radius: 4px;
            background-color: #f3be00;
        }
     
        input.first:checked+label {
            background-color: #1f8528;
            border: 2px solid #2c3750;
        }

        label.bus {
            width: 30px;
            height: 30px;
            border-radius: 4px;
            background-color: #8104ca;
        }
     
        input.bus:checked+label {
            background-color: #1f8528;
            border: 2px solid #2c3e50;
        }

        label.taken {
            width: 30px;
            height: 30px;
            border-radius: 4px;
            background-color: #686868;
        }
    </style>
{% endblock content %}